name: Valt
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  valt:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Valt
        uses: valthq/valt-action@v1
        with:
          api-key: ${{ secrets.VALT_API_KEY }}
          api-url: ${{ vars.VALT_API_URL }}
